// Generated by Dagger (https://dagger.dev).
package com.grappim.spacexapp.core.network.gets;

import com.grappim.spacexapp.data.remote.SpaceXRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GetAllLaunches_Factory implements Factory<GetAllLaunches> {
  private final Provider<SpaceXRepository> spaceXRepoProvider;

  public GetAllLaunches_Factory(Provider<SpaceXRepository> spaceXRepoProvider) {
    this.spaceXRepoProvider = spaceXRepoProvider;
  }

  @Override
  public GetAllLaunches get() {
    return newInstance(spaceXRepoProvider.get());
  }

  public static GetAllLaunches_Factory create(Provider<SpaceXRepository> spaceXRepoProvider) {
    return new GetAllLaunches_Factory(spaceXRepoProvider);
  }

  public static GetAllLaunches newInstance(SpaceXRepository spaceXRepo) {
    return new GetAllLaunches(spaceXRepo);
  }
}
