// Generated by Dagger (https://dagger.dev).
package com.grappim.spacexapp.core.network.gets;

import com.grappim.spacexapp.data.remote.SpaceXRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GetLatestLaunch_Factory implements Factory<GetLatestLaunch> {
  private final Provider<SpaceXRepository> spaceXRepoProvider;

  public GetLatestLaunch_Factory(Provider<SpaceXRepository> spaceXRepoProvider) {
    this.spaceXRepoProvider = spaceXRepoProvider;
  }

  @Override
  public GetLatestLaunch get() {
    return newInstance(spaceXRepoProvider.get());
  }

  public static GetLatestLaunch_Factory create(Provider<SpaceXRepository> spaceXRepoProvider) {
    return new GetLatestLaunch_Factory(spaceXRepoProvider);
  }

  public static GetLatestLaunch newInstance(SpaceXRepository spaceXRepo) {
    return new GetLatestLaunch(spaceXRepo);
  }
}
