// Generated by Dagger (https://dagger.dev).
package com.grappim.spacexapp.core.network.gets;

import com.grappim.spacexapp.data.remote.SpaceXRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GetNextLaunch_Factory implements Factory<GetNextLaunch> {
  private final Provider<SpaceXRepository> spaceXRepoProvider;

  public GetNextLaunch_Factory(Provider<SpaceXRepository> spaceXRepoProvider) {
    this.spaceXRepoProvider = spaceXRepoProvider;
  }

  @Override
  public GetNextLaunch get() {
    return newInstance(spaceXRepoProvider.get());
  }

  public static GetNextLaunch_Factory create(Provider<SpaceXRepository> spaceXRepoProvider) {
    return new GetNextLaunch_Factory(spaceXRepoProvider);
  }

  public static GetNextLaunch newInstance(SpaceXRepository spaceXRepo) {
    return new GetNextLaunch(spaceXRepo);
  }
}
