// Generated by Dagger (https://dagger.dev).
package com.grappim.spacexapp.core.network.gets;

import com.grappim.spacexapp.data.remote.SpaceXRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class GetUpcomingCapsules_Factory implements Factory<GetUpcomingCapsules> {
  private final Provider<SpaceXRepository> spaceXRepoProvider;

  public GetUpcomingCapsules_Factory(Provider<SpaceXRepository> spaceXRepoProvider) {
    this.spaceXRepoProvider = spaceXRepoProvider;
  }

  @Override
  public GetUpcomingCapsules get() {
    return newInstance(spaceXRepoProvider.get());
  }

  public static GetUpcomingCapsules_Factory create(Provider<SpaceXRepository> spaceXRepoProvider) {
    return new GetUpcomingCapsules_Factory(spaceXRepoProvider);
  }

  public static GetUpcomingCapsules newInstance(SpaceXRepository spaceXRepo) {
    return new GetUpcomingCapsules(spaceXRepo);
  }
}
